name: Deploy blog

on:
  push:
    branches: [main]
    paths:
      - 'contenido/posts/**'
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          cd web
          npm install

      - name: Copy Obsidian posts to Astro content
        run: |
          mkdir -p web/src/content/posts
          cp -r contenido/posts/* web/src/content/posts/
          
      - name: Build website
        run: |
          cd web
          npm run build
          
      - name: Deploy
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: tu-nombre-de-proyecto
          directory: web/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}