name: Upload Assets to R2

on:
  push:
    branches: [main]
    paths:
      - 'contenido/activos/**'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # To be able to get changed files

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v37
        with:
          files: contenido/activos/**

      - name: Install Cloudflare Workers CLI
        run: npm install -g wrangler

      - name: Upload changed assets to R2
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ -f "$file" ]]; then
              echo "Uploading $file to R2..."
              # Extraer la ruta relativa desde contenido/activos/
              relative_path=$(echo $file | sed 's|contenido/activos/||')
              # Subir el archivo a R2
              wrangler r2 object put $R2_BUCKET_NAME/$relative_path --file $file
              
              # Obtener la URL pública del archivo
              echo "Archivo subido: https://$R2_BUCKET_NAME.your-subdomain.r2.dev/$relative_path"
            fi
          done